version: "3.8"
services:
  app:
    container_name: react-ts-boilerplate_dev_container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    tty: true
